### ISSUE TITLE
有没有可能首页加上热搜音乐排行榜,点击后站内搜索

### ISSUE THREAD

**Issue by Svipa** [lifankohome/music-spider#1]

**Comment by lifankohome** [comment]
当然可以了，实现的方法可以是在使用者点击搜索按钮后，将关键词进行大爆炸分解，将其保存进数组中，对数组进行json编码（数组无法输出为文字格式，但是json可以），然后保存为一个txt文件（使用数据库或许更科学，但是有点冗余）。

当然保存进数组的时候要先读取txt文件获取历史搜索，之后进行保存，构成完整流程。

---

你也可以尝试克隆下来代码并对其进行编辑，如果你愿意的话,，请在这里留言

**Comment by lifankohome** [comment]
已经添加完成，自动显示搜索榜前10，每次点击 加载更多 会额外多显示10条
